# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: isac123'
  inputs:
    azureSubscription: 563c8932-3d5c-48e0-86bf-5ba2e59d635c
    appType: webAppLinux
    appName: isac123
    package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
